# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.messages.base_model_ import Model
from api import util


class LogsActionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, action=None):  # noqa: E501
        """LogsActionRequest - a model defined in OpenAPI

        :param action: The action of this LogsActionRequest.  # noqa: E501
        :type action: str
        """
        self.openapi_types = {
            'action': str
        }

        self.attribute_map = {
            'action': 'action'
        }

        self._action = action

    @classmethod
    def from_dict(cls, dikt) -> 'LogsActionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The logs_action_request of this LogsActionRequest.  # noqa: E501
        :rtype: LogsActionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def action(self):
        """Gets the action of this LogsActionRequest.


        :return: The action of this LogsActionRequest.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this LogsActionRequest.


        :param action: The action of this LogsActionRequest.
        :type action: str
        """
        allowed_values = ["start", "stop", "restart"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"
                .format(action, allowed_values)
            )

        self._action = action
