FROM ubuntu:14.04
MAINTAINER Xiaolei Huang <xiaoleihuangccnu@gmail.com>

RUN apt-get update -y \
&& apt-get upgrade -y \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:webupd8team/java \
    && apt-get update -y \
