/**
 * Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LogsActionRequest model module.
 * @module model/LogsActionRequest
 * @version 1.0
 */
class LogsActionRequest {
    /**
     * Constructs a new <code>LogsActionRequest</code>.
     * @alias module:model/LogsActionRequest
     * @param action {module:model/LogsActionRequest.ActionEnum} 
     */
    constructor(action) { 
        
        LogsActionRequest.initialize(this, action);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action) { 
        obj['action'] = action;
    }

    /**
     * Constructs a <code>LogsActionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LogsActionRequest} obj Optional instance to populate.
     * @return {module:model/LogsActionRequest} The populated <code>LogsActionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LogsActionRequest();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LogsActionRequest.ActionEnum} action
 */
LogsActionRequest.prototype['action'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
LogsActionRequest['ActionEnum'] = {

    /**
     * value: "start"
     * @const
     */
    "start": "start",

    /**
     * value: "stop"
     * @const
     */
    "stop": "stop",

    /**
     * value: "restart"
     * @const
     */
    "restart": "restart"
};



export default LogsActionRequest;

